-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema crestdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `crestdb` ;

-- -----------------------------------------------------
-- Schema crestdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crestdb` DEFAULT CHARACTER SET utf8 ;
USE `crestdb` ;

-- -----------------------------------------------------
-- Table `outbreak`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `outbreak` ;

CREATE TABLE IF NOT EXISTS `outbreak` (
  `id` INT NOT NULL,
  `source` VARCHAR(450) NULL,
  `date` DATETIME NULL,
  `summary` TEXT NULL,
  `disease` VARCHAR(2500) NULL,
  `location` VARCHAR(450) NULL,
  `species` VARCHAR(450) NULL,
  `cases` INT NULL,
  `deaths` INT NULL,
  `significance` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS crestdbuser@localhost;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'crestdbuser'@'localhost' IDENTIFIED BY 'crestdbuser';

GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE * TO 'crestdbuser'@'localhost';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `outbreak`
-- -----------------------------------------------------
START TRANSACTION;
USE `crestdb`;
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (1, 'World Org. for Animal Health', '2019-1-16', 'Rabbit haemorrhagic disease, United States of America', 'Other Animal Disease', 'United States', 'Non-human animal', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (2, 'Google News', '2019-07-28', 'Why so many recalls? Experts say the rise of food, drug recalls is a ...', 'Foodborne Illness', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (3, 'Google News', '2019-07-19', 'The ABCs Of Hepatitis C - Long Island Weekly News', 'Hepatitis C', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (4, 'Google News', '2019-07-19', 'U.S. CDC links two deaths to multi-state salmonella outbreak - Reuters', 'Salmonella', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (5, 'Google News', '2019-07-19', 'asdasda - Tri-State Livestock News', 'BSE', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (6, 'Google News', '2019-07-19', 'Headlines for Friday, July 19, 2019 - kansaspublicradio.org', 'Not Yet Classified', 'Kansas, United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (7, 'Google News', '2019-07-19', 'Amid National Hepatitis A Outbreaks, Kansas Requires Vaccine For ...', 'Hepatitis A', 'Kansas, United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (8, 'Google News', '2019-07-19', 'Colby pond added to state\'s algae warning list - Hays Post', 'Algae', 'Kansas, United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (9, 'Google News', '2019-07-19', 'White-Nose Syndrome Is Devastating Bats In The East And Is Predicted ...', 'White nose syndrome', 'Utah, United States', 'Bats', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (10, 'Google News', '2019-07-19', 'West Nile discovered in Douglas County for the first time this year - ...', 'West Nile Virus', 'Nebraska, United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (11, 'Google News', '2019-07-20', 'Colorado horses contracting painful virus - FOX 31 Denver', 'Vesicular Stomatitis', 'Colorado, United States', 'Livestock (domestic)', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (12, 'Google News', '2019-07-20', 'Getting Eaten Alive By Mosquitoes? Here\'s All You Ever Needed to Know ...', 'West Nile Virus', 'United States', 'Mosquito', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (13, 'Google News', '2019-07-20', 'Global Drugs for Leishmaniasis (Kala-Azar) Market Size, Share & ...', 'Leishmaniasis', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (14, 'Google News', '2019-07-20', '19 Additional Polio Cases Reported - Vax Before Travel', 'Polio', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (15, 'Google News', '2019-07-20', 'ENJOYING NATURE: Should you worry about rabies? | Glade Sun - ...', 'Rabies', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (16, 'Google News', '2019-07-20', 'CDC calls for vigilance after dengue case missed - 台北時報', 'Dengue', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (17, 'Google News', '2019-07-20', 'Moroccan Woman Aims to Make Tangier the First Rabies-Free City in ...', 'Rabies', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (18, 'Google News', '2019-07-20', 'CDC issues travel notice for Bolivia due to outbreak of hemorrhagic ...', 'Hemorrhagic Fever', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (19, 'Google News', '2019-07-21', 'Japan undecided on response to U.S. plan for Mideast maritime ...', 'Not Yet Classified', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (20, 'Google News', '2019-07-21', 'Mountain Rose Herbs Recalls Fennel Seed Whole Because of Possible ...', 'Salmonella', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (21, 'Google News', '2019-07-21', 'CDC supports WHO declaration of “Public Health Emergency of ...', 'Ebola', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (22, 'Google News', '2019-07-21', '2-year-old battles cancer and rare polio-like disease - KETV Omaha', 'Polio', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (23, 'Google News', '2019-07-21', 'Illegal Immigrants Coming to US for Surgery: McAleenan - The Epoch ...', 'Influenza', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (24, 'Google News', '2019-07-21', 'CDC Food Safety Alert: E. coli. Outbreak Linked to Ground Bison - ...', 'E. coli', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (25, 'Google News', '2019-07-21', 'STDs Diagnosis Market is Booming Worldwide | Point-Of-Care (POC) ...', 'Sexually Transmitted Infection', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (26, 'Google News', '2019-07-21', 'Here\'s how Utah public health workers battled last year\'s hepatitis A ...', 'Hepatitis A', 'Utah, United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (27, 'Google News', '2019-07-22', 'VSV Remains Confined to Three States - Drovers Magazine', 'Vesicular Stomatitis', 'Colorado, United States', 'Livestock (domestic)', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (28, 'Google News', '2019-07-22', 'Denver health officials warn of hepatitis A outbreak - 9News.com KUSA', 'Hepatitis A', 'Colorado, United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (29, 'Google News', '2019-07-22', 'Virus prompts animal quarantines in Larimer, Weld and Boulder ...', 'Not Yet Classified', 'Colorado, United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (30, 'Google News', '2019-07-22', 'These Are the Recommended Vaccines for Teens - U.S. News & World ...', 'Meningitis', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (31, 'Google News', '2019-07-22', 'V(a)x populi: Should we or should we not vaccinate - Down To Earth ...', 'Measles', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (32, 'Google News', '2019-07-22', 'Vaccines for Teens - Yahoo News', 'HPV', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (33, 'Google News', '2019-07-22', 'Global Global Intravenous Immunoglobulin Market 2019-2024: Historical ...', 'Pelvic Inflammatory Disease', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (34, 'Google News', '2019-07-22', 'Comparing of Midatech Pharma Plc (MTP) and Soligenix Inc. ...', 'Thrush', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (35, 'Google News', '2019-07-22', 'CDC Urges Rapid Reporting of AFM Ahead of Prime Season - ...', 'Polio', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (36, 'ProMED Mail', '2019-07-22', 'PRO/AH/EDR> Salmonellosis, st I 4,[5],12:i:- - USA (02): pig ear dog ...', 'Salmonella', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (37, 'Google News', '2019-07-22', 'Recall Roundup: Pasta sauce contains plastic fragments; listeria ...', 'Listeriosis', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (38, 'Google News', '2019-07-22', 'Listeria Fears Prompt Target, Fresh Market Recalls - WebMD', 'Listeriosis', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (39, 'ProMED Mail', '2019-07-22', 'PRO/PL> Pod wart disease, peanut - Americas: 1st rep (USA)', 'Other Plant Disease', 'United States', 'Plants', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (40, 'Google News', '2019-07-22', 'U.S. RECORDS 25 NEW CASES OF MEASLES IN WEEK ENDED JULY 18, BRINGING ...', 'Measles', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (41, 'Google News', '2019-07-22', 'HHS, DoD, VenatoRx Pharmaceuticals to Co-Develop Novel Antibiotic to ...', 'Carbapenem-resistant enterobacteriaceae (CRE)', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (42, 'Google News', '2019-07-22', 'Veterinary Anti-Infectives Market: What it got next? Find out with ...', 'Foodborne Illness', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (43, 'Google News', '2019-07-23', 'Splash pads safe after recent scare in Colorado Springs - ...', 'Hand, Foot and Mouth Disease', 'Colorado, United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (44, 'Google News', '2019-07-23', 'new-guidelines-call-for-meningitis-hepatitis-vaccinations - Leader & ...', 'Hepatitis', 'Colorado, United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (45, 'Google News', '2019-07-23', 'CDC: Measles now reported in 30 states including Colorado - ...', 'Measles', 'Colorado, United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (46, 'Google News', '2019-07-23', 'West Nile virus shows up in Allentown - PhillyVoice.com', 'West Nile Virus', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (47, 'Google News', '2019-07-23', 'Rep. McCaul continues to urge US action to halt Ebola outbreak - ...', 'Ebola', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (48, 'Google News', '2019-07-23', 'Measles continues to spread - WNYT', 'Measles', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (49, 'Google News', '2019-07-23', 'How a pair of rude gut germs perfectly summarize our war against ...', 'Not Yet Classified', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (50, 'Google News', '2019-07-23', 'A year for fall oats - Hay & Forage Grower', 'Other Plant Disease', 'United States', 'Plants', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (51, 'Google News', '2019-07-23', 'Medical school students: Detained migrants still have a right to ...', 'Not Yet Classified', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (52, 'Google News', '2019-07-23', 'Syphilis cases reach all-time high in Europe, up 70% in 7 years - ...', 'Syphilis', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (53, 'ProMED Mail', '2019-07-23', 'PRO/EDR> Hepatitis A - USA (26): CDC', 'Hepatitis A', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (54, 'ProMED Mail', '2019-07-23', 'PRO/AH/EDR> Salmonellosis - USA (03): live poultry, multiple ...', 'Salmonella', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (55, 'ProMED Mail', '2019-07-23', 'PRO/EDR> Measles update (51): RFI', 'Measles', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (56, 'Google News', '2019-07-23', 'Deadly fungal disease may be linked to climate change, study suggests ...', 'Chronic/Non-Infectious Disease', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (57, 'Google News', '2019-07-23', 'Kansas vaccine rules are changing, but why? - KCTV Kansas City', 'Meningitis - Neisseria', 'Kansas, United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (58, 'Google News', '2019-07-23', 'Most of Kansas at high risk for West Nile virus - KAKE', 'West Nile Virus', 'Kansas, United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (59, 'Google News', '2019-07-23', 'Two confirmed cases of dog flu in Utah - KUTV 2News', 'Canine Influenza', 'Utah, United States', 'Dogs', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (60, 'Google News', '2019-07-24', 'How A \'Perfect Storm\' Cut Off Water To This Colorado Town - NPR', 'Waterborne Illness', 'Colorado, United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (61, 'Google News', '2019-07-24', 'Pollution Problems, Beach Closures Plague Many U.S. Beaches - ecoRI ...', 'Plague', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (62, 'Google News', '2019-07-24', 'The Last Days of John Allen Chau - Outside', 'Conflict', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (63, 'Google News', '2019-07-24', 'Hundreds of Salmonella cases reported across 48 states - WWLP.com', 'Salmonella', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (64, 'ProMED Mail', '2019-07-24', 'PRO/AH/EDR> Bovine tuberculosis - USA (05): (MI) cattle', 'Bovine TB', 'United States', 'Cows', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (65, 'ProMED Mail', '2019-07-24', 'PRO/AH/EDR> Rabies (38): Americas (Canada, USA) bat, fox, kitten, ...', 'Rabies', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (66, 'Google News', '2019-07-24', 'Hillsboro Free PressIncoming students will need new vaccines before ...', 'Hepatitis A', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (67, 'Google News', '2019-07-24', 'One case of equine virus found in Johnson County - Cleburne ...', 'Vesicular Stomatitis', 'United States', 'Livestock (domestic)', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (68, 'Google News', '2019-07-24', 'The Consequences of Not Getting Vaccinated - Pharmacy Times', 'Influenza', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (69, 'Google News', '2019-07-24', 'Changes in HIV PrEP Awareness and Use Among MSM - Medscape', 'HIV/AIDS', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (70, 'Google News', '2019-07-24', 'Jamaican travellers warned to protect themselves against measles - ...', 'Measles', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (71, 'Google News', '2019-07-24', 'Batwoman: Saving bats and restoring the population with one nonprofit ...', 'White nose syndrome', 'United States', 'Bats', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (72, 'Google News', '2019-07-24', 'Senate Finance Committee Issues Testimony From HHS Office of ...', 'Pneumonia', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (73, 'Google News', '2019-07-24', 'These tips can help you have a safe, healthy and happy summer - Beach ...', 'Cryptosporidium', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (74, 'Google News', '2019-07-24', 'Baloxavir Shows Broad Antiviral Activity Against Influenza A, B, C, ...', 'Influenza', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (75, 'ProMED Mail', '2019-07-24', 'PRO/EDR> Japanese encephalitis: vaccine recommendations, CDC', 'Japanese Encephalitis', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (76, 'Google News', '2019-07-24', 'Gonorrhea Diagnostic Market to See Worldwide Growth by 2026: Leading ...', 'Gonorrhea', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (77, 'ProMED Mail', '2019-07-25', 'PRO/AH/EDR> Vesicular stomatitis - USA (07): (TX,CO,NM) horse', 'Vesicular Stomatitis', 'Colorado, United States', 'Livestock (domestic)', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (78, 'Google News', '2019-07-25', 'Health Investigation Underway After Metro State University Of Denver ...', 'Chronic/Non-Infectious Disease', 'Colorado, United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (79, 'Google News', '2019-07-25', 'Gurugram: Rabies vaccine back in stock - Times of India', 'Rabies', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (80, 'Google News', '2019-07-25', 'News Scan for Jul 25, 2019 - CIDRAP', 'MERS', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (81, 'Google News', '2019-07-25', 'CDC investigating cases of acute flaccid myelitis, a polio-like virus ...', 'Polio', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (82, 'Google News', '2019-07-25', 'U.S. firms keen on China\'s import expo despite trade frictions - ...', 'Not Yet Classified', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (83, 'Google News', '2019-07-25', 'Trapping female mosquitoes helps curb chikungunya virus - Science ...', 'Chikungunya', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (84, 'Google News', '2019-07-25', 'CORRECTED-Sweden charges U.S. rapper A$AP Rocky with assault - Yahoo ...', 'Not Yet Classified', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (85, 'Google News', '2019-07-25', 'A lawsuit challenges the way the FDA deals with salmonella and ...', 'Listeriosis', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (86, 'ProMED Mail', '2019-07-25', 'PRO/AH/EDR> Powassan virus encephalitis - USA (02): (ME)', 'Tick-borne Encephalitis', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (87, 'Google News', '2019-07-25', 'Airlines relying on parents to carry child-friendly medicines – ...', 'Not Yet Classified', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (88, 'ProMED Mail', '2019-07-25', 'PRO/AH/EDR> Vesicular stomatitis - USA (07): (TX,CO,NM) horse', 'Vesicular Stomatitis', 'United States', 'Livestock (domestic)', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (89, 'Google News', '2019-07-25', 'Ninety-five undergraduates to present summer research - KU Today', 'Chronic/Non-Infectious Disease', 'Kansas, United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (90, 'Google News', '2019-07-25', 'UPDATE: KDHE issues algae warning for Lebo Kids Pond Featured - KVOE', 'Algae', 'Kansas, United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (91, 'Google News', '2019-07-25', 'Wichita on track for EPA loan, new water treatment plant - Wichita ...', 'Environmental', 'Kansas, United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (92, 'Google News', '2019-07-25', 'Meningitis vaccine clinic set - News - The Hutchinson News', 'Meningitis', 'Kansas, United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (93, 'Google News', '2019-07-26', 'Colorado\'s Ongoing Fight to End HIV - 5280 | The Denver Magazine', 'HIV/AIDS', 'Colorado, United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (94, 'Google News', '2019-07-26', 'Toasting Up an Acquisition and OpenTable Truly Delivers - Modern ...', 'Not Yet Classified', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (95, 'Google News', '2019-07-26', 'The rise of a deadly superfungus may be tied to global warming - ...', 'Not Yet Classified', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (96, 'Google News', '2019-07-26', 'The United States Treats Migrants Worse Than Prisoners of War - ...', 'Chronic/Non-Infectious Disease', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (97, 'Google News', '2019-07-26', 'FDA blames bad basil for foodborne illnesses in several states - WTOP', 'Foodborne Illness', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (98, 'Google News', '2019-07-26', 'Comparing of NantKwest Inc. (NK) and Soligenix Inc. (NASDAQ:SNGX) - ...', 'Chronic/Non-Infectious Disease', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (99, 'Google News', '2019-07-26', 'Guatemala document says US migration deal to last 2 years - Yahoo News', 'Not Yet Classified', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (100, 'Google News', '2019-07-26', 'Heavyweight Dillian Whyte Tests Positive for Dianabol Metabolites - ...', 'Not Yet Classified', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (101, 'Google News', '2019-07-26', 'McCarthy Leads Bicameral Letter to Incentivize Investment in Valley ...', 'Valley Fever', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (102, 'Google News', '2019-07-26', 'These Are the 5 Vaccines Every Adult Needs - Yahoo Lifestyle', 'Influenza', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (103, 'Google News', '2019-07-26', 'No, Lyme disease is not an escaped military bioweapon, despite what ...', 'Lyme Disease', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (104, 'ProMED Español', '2019-07-26', 'PRO/ESP> Salmonella - EEUU: (MULTIESTADOS) brote, personas y ...', 'Salmonella', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (105, 'ProMED Español', '2019-07-26', 'PRO/ESP> Sarampión - EEUU: (08) (MULTIESTADOS) brote, aumento de ...', 'Measles', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (106, 'ProMED Mail', '2019-07-26', 'PRO/EDR> Acute flaccid myelitis - North America (07): USA, CDC alert', 'Other Human Disease', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (107, 'Google News', '2019-07-26', 'Health websites are notoriously misleading. So we rated their ...', 'Measles', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (108, 'Google News', '2019-07-26', 'EEE virus found in six mosquitoes in Rehoboth | Local News - The Sun ...', 'Eastern Equine Encephalitis', 'Utah, United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (109, 'Google News', '2019-07-26', 'Canned catastrophe: botulism case gives doctors chance to study rare ...', 'Botulism', 'Utah, United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (110, 'Google News', '2019-07-26', 'West Nile Virus detected in central Utah - KSTU FOX 13 Salt Lake City', 'West Nile Virus', 'Utah, United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (111, 'ProMED Mail', '2019-07-26', 'PRO/PL> Cercospora leaf spot, sugar beet - USA: (NE)', 'Other Plant Disease', 'Nebraska, United States', 'Crops', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (112, 'Google News', '2019-07-27', 'VSV spreads to 11 counties including Morgan - Journal Advocate', 'Vesicular Stomatitis', 'Colorado, United States', 'Livestock (domestic)', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (113, 'ProMED Mail', '2019-07-27', 'PRO/EDR> Cyclosporiasis - USA (04): imported basil, Mexico, susp., ...', 'Foodborne Illness', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (114, 'Google News', '2019-07-27', 'July 2009: H1N1 influenza claims Portage County - Stevens Point News', 'Influenza H1N1', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (115, 'ProMED Español', '2019-07-27', 'PRO/ESP> Cyclospora- EEUU (MULTIESTADO) albahaca fresca importada, ...', 'Protozoa, miscellaneous', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (116, 'Google News', '2019-07-27', 'Can Kratom cause a false positive on a 12-panel drug test? - Augusta ...', 'Salmonella', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (117, 'ProMED Mail', '2019-07-28', 'PRO/AH/EDR> Vesicular stomatitis - USA (08): (CO) horses', 'Vesicular Stomatitis', 'Colorado, United States', 'Livestock (domestic)', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (118, 'Google News', '2019-07-28', 'Lab techs extract mosquito DNA defense against West Nile - KTVZ', 'West Nile Virus', 'Colorado, United States', 'Mosquito', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (119, 'Google News', '2019-07-28', 'Syphilis Diagnosis Kit Market Scope and Overview Forecast 2019 to ...', 'Syphilis', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (120, 'ProMED Mail', '2019-07-28', 'PRO/AH/EDR> Influenza (22): USA (MI) swine origin, pigs, fair', 'Influenza', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (121, 'ProMED Mail', '2019-07-28', 'PRO/AH/EDR> Vesicular stomatitis - USA (08): (CO) horses', 'Vesicular Stomatitis', 'United States', 'Livestock (domestic)', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (122, 'Google News', '2019-07-28', 'On World Hepatitis Day the U.S. is Battling an Outbreak - Newsweek', 'Hepatitis', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (123, 'Google News', '2019-07-28', 'Medical Guide 2019: Get the facts on measles to remain protected - ...', 'Measles', 'United States', 'Humans', NULL, NULL, NULL);
INSERT INTO `outbreak` (`id`, `source`, `date`, `summary`, `disease`, `location`, `species`, `cases`, `deaths`, `significance`) VALUES (124, 'Google News', '2019-07-29', 'Checkup Denver: Opioid pills flow in Colorado, hepatitis A outbreak ...', 'Hepatitis A', 'Colorado, United States', 'Humans', NULL, NULL, NULL);

COMMIT;

